
name: auto-crawl

on:
  schedule:
    - cron: "30 16 * * *"
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync
    - name: Run script
      run: |
        source .venv/bin/activate
        export EMAIL_USERNAME=${{secrets.EMAIL_USERNAME}}
        export EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}}
        export EMAIL_TO=${{secrets.EMAIL_TO}}
        bash run.sh
      
